-- ============================================================
-- migracion 006: drop legacy CHECK points_description_check
-- ============================================================
-- La migracion 005 tenia un bug en su DO block: buscaba el CHECK
-- viejo con ilike '%description%between%10%', pero Postgres almacena
-- la definicion sin la palabra "between" — la traduce a "(>= 10) AND
-- (<= 1000)". El pattern no matcheo, el CHECK viejo quedo activo
-- junto con el nuevo points_has_evidence.
--
-- Sintoma: foto + descripcion entre 1-9 chars era rechazada por el
-- CHECK viejo (>= 10 chars) aunque la regla del MVP es "si pones
-- descripcion, minimo 10 chars" — ese min se enforce en zod (cliente
-- + server), no en SQL. SQL solo debe enforce "al menos uno presente"
-- (eso lo hace points_has_evidence).
--
-- Verificacion previa esperada (debe mostrar el CHECK legacy):
--   select conname, pg_get_constraintdef(oid)
--   from pg_constraint
--   where conrelid = 'public.points'::regclass and contype = 'c';
--
-- Drop directo por nombre. Idempotente con IF EXISTS — si por alguna
-- razon ya fue removido, es no-op.
-- ============================================================

alter table public.points
  drop constraint if exists points_description_check;

-- ============================================================
-- Verificacion post-migracion (correr en SQL Editor despues):
-- ============================================================
-- select conname, pg_get_constraintdef(oid)
-- from pg_constraint
-- where conrelid = 'public.points'::regclass and contype = 'c'
-- order by conname;
--
-- Resultado esperado:
--   points_has_evidence  -> CHECK ((photo_url IS NOT NULL) OR ...
--   (algunos checks inline de lat/lng con nombres auto-generados)
--
-- NO debe aparecer points_description_check.
-- ============================================================
